### PR TITLE
modified of stm32h7 files

### PR DESCRIPTION
**Pull request by jfbblue0922**
Summary
・In order to compile PX4-Autopilot with stm32h755II, I modified it to enable CONFIG_STM32H7_STM32H7X5XX.
・Added 'ARMV7M_HAVE_XXX' to the definition of STM32H7_STM32H7X5XX in the Kconfig file.

Impact
Use the CONFIG_STM32H7_STM32H7X5XX define.

Testing
We have confirmed that the firmware works correctly on PX4.

### CODE REVIEW

**Comment by davids5** [comment]
@jfbblue0922  is this already in upstream NuttX?

**Comment by jfbblue0922** [comment]
@davids5 

This already in upstream NuttX.
- Upstream already provides the compile switch CONFIG_STM32H7_STM32H7X5XX to configure the stm32h7x5.
- Upstream provides ARCH_CHIP_STM32H7_CORTEXM7 to select core of the STM32H7x5.
 
For this reason, I think upstream PR is not necessary.
Thank you.

**Comment by davids5** [comment]
> @davids5
> 
> This already in upstream NuttX.
> 
> * Upstream already provides the compile switch CONFIG_STM32H7_STM32H7X5XX to configure the stm32h7x5.
> * Upstream provides ARCH_CHIP_STM32H7_CORTEXM7 to select core of the STM32H7x5.
> 
> For this reason, I think upstream PR is not necessary. Thank you.

Then this is a partial Backport. Please change the commit message to say `[BACKPORT] stm32h7: STM32H7X5XX selects hardware files`

**Review by davids5 — CHANGES_REQUESTED** [review]
Then this is a partial Backport. Please change the commit message to say `[BACKPORT] stm32h7: STM32H7X5XX selects hardware files`

**Comment by jfbblue0922** [comment]
@davids5

I changed the commit message.

**Comment by davids5** [comment]
@jfbblue0922 We need to build test this:

Please create a PR in PX4 that updates the `platforms/nuttx/NuttX/nuttx` to this commit.

Use `NuttX with stm32h7: STM32H7X5XX backport' as the commit message.

**Comment by davids5** [comment]
@jfbblue0922 Did you create the PX4 PR?

**Comment by davids5** [comment]
@jfbblue0922 Please rebase this on the current [px4_firmware_nuttx-10.3.0+](https://github.com/PX4/NuttX/tree/px4_firmware_nuttx-10.3.0%2B) and create the PX4 PR to bring it in.

**Comment by jfbblue0922** [comment]
@davids5 
I rebased this PR on the current px4_firmware_nuttx-10.3.0+.
Then should I make a PR at https://github.com/PX4/PX4-Autopilot ?

**Comment by davids5** [comment]
> @davids5 I rebased this PR on the current px4_firmware_nuttx-10.3.0+. Then should I make a PR at https://github.com/PX4/PX4-Autopilot ?

Yes.  It points PX4 auto pilot to the nuttx changes you made for testing.

```
git fetch  < px4 remote >
git checkout main
git submodule sync --recursive && git submodule update --init --recursive
git checkout -b pr-stm32h7-update
cd platforms/nuttx/NuttX/nuttx/
git checkout < your nuutx branch >
cd ../../../../
git commit platforms/nuttx/NuttX/nuttx/ -m"Nuttx with stm32h7: STM32H7X5XX selects hardware files backport"
git push -f < your remote for PX4> pr-stm32h7-update
```
Then open a PX4 PR.

**Comment by jfbblue0922** [comment]
@davids5
I would like to do a git checkout < your nuutx branch >
but I get the error: pathspec 'pr-stm32h755II-2' did not match any file(s) known to git.
How do I checkout the 'pr-stm32h755II-2' branch?

**Comment by jfbblue0922** [comment]
@davids5 
I made a PX4 PR.
Thank you.

**Pull request merged**
