### PR TITLE
Build fixes for compiling NuttX with Eigen

### PR DESCRIPTION
**Pull request by Zefz**
Adds some missing macro definitions to ```ctype.h``` which are required to get Eigen to compile.

It also modifies time struct ```tm``` adding some data fields that were commented out ```/*not supported*/``` (required by Eigen as well).

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome, thanks! @davids5

**Comment by nuttx** [comment]
This does not look appropriate for upstream NuttX.  There are two basic challenges and the will not be accepted upstream:

1. Definition of bit maps.  Not used in NuttX.  Defining these would be a timebomb since any use of them is inherently wrong.

2. Unused fields in struct tm are uncommented.  This is less lethal, but certainly is not desireable, expecially for parts with highly constrained memory usage.

**Comment by LorenzMeier** [comment]
@nuttx I'd like to do a bit more readup on the C++ standard before drawing any conclusions, and this patch set wasn't submitted upstream because we know there is more evaluation to be done.

**Comment by nuttx** [comment]
I am *very* picky about what goes into NuttX header files.  I don't accept non-standardized changes to go into them just to permit external code to compile; nor do I accept changes that imply something is implemented when it is not (although there are cases like that in the code).

While I refuse to put such non-standard or useless stuff in NuttX header files, there are ways to work around this.  Here is somoething that I proposed to David:  Suppose there is a directory called myincludes/ and in myincludes/ is a header called ctype.h.  In this ctype.h is:

#define _U  01
#define _L  02
#define _N  04
#define _S  010
#define _P  020
#define _C  040
#define _X  0100
#define _B  0200

#include_next <ctype.h>

And suppose that there is another header time.h that looks like this:

#define tm __tm
#include_next <time.h>

struct tm
{
  int tm_sec;     /* Seconds (0-61, allows for leap seconds) */
  int tm_min;     /* Minutes (0-59) */
  int tm_hour;    /* Hours (0-23) */
  int tm_mday;    /* Day of the month (1-31) */
  int tm_mon;     /* Month (0-11) */
  int tm_year;    /* Years since 1900 */
  int tm_wday;    /* Day of the week (0-6) */
  int tm_yday;    /* Day of the year (0-365) */
  int tm_isdst;   /* Non-0 if daylight savings time is in effect */
};

Then in your CFLAGS, you use an -isystem setting to include files from myincludes/ before nuttx/includes. In this way you an append or modify any of the NuttX header files with my having to accept changes that I do not want upstream.

Here is an example where I used this technique in the past to graft MMU-less shared memory support into uClibc++: http://xflat.cvs.sourceforge.net/viewvc/xflat/xflat/arch-include/ .  Works nicely and gives you independent control over the content of header files.

Greg

**Comment by davids5** [comment]
@Zefz  Please let me know once you have a build with Eigen in the Firmware repo.

For the short term, we will use the "PX4 build time patching" from the nuttx-patches directory. (It is old school but easy to understand) I will generate a PR to your PR for Eigen in the Firmware repo that will add the patches.

For the long term:

I will research the usage of the #defines from ctype.h to determine how and if their usage is a legitimate c++ requirement/dependance or just a use of an implementation detail that should be carpartimantlized.

Once that is sorted, out we can discuss what is the best long term way to move forward with these ctype.h related changes.

On the issues of time.h 

The long term solution would be as follows as follows:

Greg is open to incorporate a patch upstream, If we provide the code to support the implementation of the extended time functions:
```
Day of the week 
Day of the year 
Is daylight savings time is in effect
```
wrapped in CONFIG_TIME_EXTENDED 

That is on my list to do.

**Comment by Zefz** [comment]
@davids5 Eigen is now added to the PX4 repository through this pull request:
https://github.com/PX4/Firmware/pull/1929

**Comment by davids5** [comment]
@Zefz Sorry for the delay. I have submitted patches https://github.com/PX4/NuttX/commit/6c18397707a17eb2097f4957fb4355a46398958d to Greg in support of the nuttx/include/time.h extension. nuttx_next currently has those changes applied for testing. As far as the ctype.h changes. These are being handled as buildtime patching in the nuttx next branch.

There still the concern of binary incompatibilities due to the inclusion of toolchain header files that need to be scrutinized and in the long term resolved.

**Comment by davids5** [comment]
@LorenzMeier the patches have been submitted.

**Comment by LorenzMeier** [comment]
@Zefz This is applied to our current WIP branch and David is working on the more long-term solution with Greg.

**Pull request closed without merging**
