### PR TITLE
Update work_thread.c

### PR DESCRIPTION
**Pull request by ultrasystem**
Here wrong?

### CODE REVIEW

**Comment by nuttx** [comment]
I think you are right.  I incorporated the change upstream as well.  The code is very different, but it should be the same bug fix: http://sourceforge.net/p/nuttx/git/ci/a9137270348022c765557cbe8c506a573304ad57/

This fix only applies to delayed work.  This should not actually be the source of major problems in typical usage.   The main purpose of the work queue is for the immediate processing of interrupt-related and that is controlled via signals.  But the work queue can also be used to perform delayed work.  In this case, the bug could cause the delayed work to be performed with a error in timing of probably 40 milliseconds in the default configuration.

Thanks!  Good find.

Greg

**Comment by ultrasystem** [comment]
Hi Greg， In this function, I found it a delay is uncertain, it's working very good in start, but becomes very short delay after a few seconds, then went back to the normal range, the same as at the beginning

**Comment by LorenzMeier** [comment]
@davids5 could you get this also into our WIP branches and update the reference to Gregs upstream version?

**Comment by ultrasystem** [comment]
@LorenzMeier Do you received my e-mail?

**Comment by LorenzMeier** [comment]
Applying this in the master branch, as we will want to hot fix it as long as we haven't switched for the production version to NuttX upstream yet. Since we will trash this branch at that point, its ok to have a different commit.

**Pull request merged**
