### PR TITLE
I2C txe interrupt storm fix fix

### PR DESCRIPTION
**Pull request by davids5**
@PX4/testflights Please test this on the Pxihawk 4 and mini. Verify both Mags always start. Then fly.

### CODE REVIEW

**Comment by davids5** [comment]
@dagar - waiting on upstream acceptance and test data.

**Comment by Junkim3DR** [comment]
Hello, we are unable to download the .px4 file.

image

**Review by LorenzMeier — DISMISSED** [review]

**Comment by davids5** [comment]
@LorenzMeier I have another change I want to make.

**Comment by LorenzMeier** [comment]
@davids5 When do you expect to have your 2nd fix in? I would like to really press ahead with this.

**Review by LorenzMeier — APPROVED** [review]

**Comment by LorenzMeier** [comment]
Looks like the fix is in.

**Comment by davids5** [comment]
@DanielePettenuzzo, @LorenzMeier, @dagar 

Findings:

1) There was a condition that would cause an IRQ storm. Random and targeted  1 ms clamping on the SDA line simulating noise would cause the lock up. This PR fixes that.

2) The twisted pair approach, may minimize cross-talk, but a copper shield could be a better* solution for impulse isolation. *The increase in capacitance will need to be checked, as to not cause more switching delay on the longer runs.

3) The percounts avg and load of the system tested with the same params was higher than master. My assumption was the higher interrupt rates for the comms. But I could not confirm that.  I spent a little time on looking for the cause: stopping mavlink and the lidar but none of these actions dropped the perfcounts avg to that of master. I would suggest we determine the root cause!

4) The perfcount avg for the ist8310 on the gps was ~130 counts higher than the onboard. Significantly higher (>200 and increasing) is a valid determination of noise causing errors and I2C resets. The resets will block the HP works for 30us per reset but if the slave device is hung it it could delay up to 900 us.
**So with motors running look for rapid increase in the off board I2C devices as an indication of noise or wiring issues.**

**Pull request merged**
