### PR TITLE
STM32 H7x7xx fixes

### PR DESCRIPTION
**Pull request by royratcliffe**

### CODE REVIEW

**Comment by dagar** [comment]
Perhaps you'd be interested in helping us move to latest upstream NuttX (https://github.com/apache/nuttx)?

**Comment by royratcliffe** [comment]
> Perhaps you'd be interested in helping us move to latest upstream NuttX (https://github.com/apache/nuttx)?  

I would indeed. Thanks @dagar.

**Comment by davids5** [comment]
@royratcliffe please add [[BACKPORT]](https://github.com/PX4/NuttX/commits/px4_firmware_nuttx-10.3.0%2B) to all the commits that are backports. Please round trip (upstream and back port) any that are not back ports.

**Comment by royratcliffe** [comment]
> @royratcliffe please add [[BACKPORT]](https://github.com/PX4/NuttX/commits/px4_firmware_nuttx-10.3.0%2B) to all the commits that are backports. Please round trip (upstream and back port) any that are not back ports.

Thanks, David. Will do. I'm currently working on a dual-core H747AI-based flight controller for Heliguy; it's just rough-and-ready work at the moment, trying to find the path of least resistance. Perhaps I was a bit too hasty to draft a pull request. I was planning to squash the commits when ready.

**Pull request closed without merging**
