### PR TITLE
ctype.h (and cctype) must define functions in global namespace for C++.

### PR DESCRIPTION
**Pull request by CarloWood**
My mistake... for some reason I thought that &lt;cctype&gt; only
defined the functions in namespace std.

But correct is that, as it was before, in C, ctype.h defines
macro's, and in C++, it defines functions in global namespace.
While cctype in C++, include ctype.h (defining functions in
global namespace) AND includes them in namespace std with
the usual namespace std { using std::isspace; ... etc list.

### CODE REVIEW

**Comment by davids5** [comment]
@CarloWood - are you on Skye today?

**Comment by davids5** [comment]
I think there is more to it then this PR is doing. 

We are pulling in foreign headers from the arm-none-eabi toolchain. This is bad, because of binary compatibility with nuttx's definitions! But we can survive it if and only if there are no OS defined types that collide. I.e. FILE.

The UnDefines are critical to the c++ layering around the ctype.h defines.....

```
In file included from Firmware/build_px4fmu-v2_default/px4fmu-v2/NuttX/nuttx-export/include/cxx/cctype:43:0,
                 from gcc-arm-none-eabi-5_4-2016q2/arm-none-eabi/include/c++/5.4.1/bits/localefwd.h:42,
                 from gcc-arm-none-eabi-5_4-2016q2/arm-none-eabi/include/c++/5.4.1/string:43,
                 from gcc-arm-none-eabi-5_4-2016q2/arm-none-eabi/include/c++/5.4.1/stdexcept:39,
                 from gcc-arm-none-eabi-5_4-2016q2/arm-none-eabi/include/c++/5.4.1/array:38,
                 from gcc-arm-none-eabi-5_4-2016q2/arm-none-eabi/include/c++/5.4.1/tuple:39,
                 from gcc-arm-none-eabi-5_4-2016q2/arm-none-eabi/include/c++/5.4.1/functional:55,
                 from Firmware/src/include/../platforms/px4_subscriber.h:42,
                 from Firmware/src/include/../platforms/px4_nodehandle.h:42,
                 from Firmware/src/include/px4.h:46,
                 from Firmware/src/platforms/nuttx/px4_nuttx_impl.cpp:40:
```

The local support in localefwd.h expects the 
```
#undef isspace
#undef isascii
#undef isprint
#undef isgraph
#undef iscntrl
#undef islower
#undef isupper
#undef isalpha
#undef isblank
#undef isdigit
#undef isalnum
#undef ispunct
#undef isxdigit
#undef toupper
#undef tolower
```

in <cctype> to undefine the previous definition so it may overload them with it's replacements adding the locale version.

So the  conclusion I draw is: cctype job is to remove the previous declaration  to allow the layering.

**Comment by CarloWood** [comment]
@davids5 I guess we need to talk on skype, but I'm about to go to bed now :/. My first impression however is that if we're including ctype.h from the arm-none-eabi toolchain when including the cctype from nuttx then something is indeed seriously wrong. Can you please tell me which config target does this? I'd like to look into this so I understand what is happening.

On another note, I am trying to (and I think I am) compiling all targets; and this compiles. So, if that's correct then there isn't a problem: it works.

**Comment by CarloWood** [comment]
Oh,... ok you listed the what is including what... So, you're saying that arm-none-eabi/include/c++/5.4.1/bits/localefwd.h includes <cctype>, which is from nuttx, and (obviously) won't compile when the ctype defines are macro's... That is what I said before: C++ wanted to overload isspace, isprint, etc with a locale parameter (which is done in localefwd.h) and that can only be done when isspace, isprint, etc are functions and not macro's. Hence, that while these things were first macro's in C, in C++ they are not macro's but functions.

My PR does that. After #87 there are no macro's (because they are #undef'd), and after this PR there are STILL no macro's, because they are never defined. The difference before and after this PR is that now the *functions* are also defined in global namespace when including <cctype> and they are still functions (and not macro's) when a C++ source includes <ctype.h> directly. Hence, this PR is correct, the previous one wasn't.

**Comment by davids5** [comment]
@CarloWood -

I was wrong. The error I was seeing was because of a hack in px4_defines.h The undefs are not needed. Yeah!

I was able to get this to work on nuttx_v3  https://github.com/PX4/Firmware/pull/4451/commits/6dc4ccf91b6c30d227a845de6484b169bd12bbaf

With the latest upstream nuttx and the patch for shadow wanings.

The #defines 
```
#define _U  01
#define _L  02
#define _N  04
#define _S  010
#define _P  020
#define _C  040
#define _X  0100
#define _B  0200
```
are not need that was hack for eigen.

So how about backporting the two files from upstream nuttx and include the shadow patch in the code. 

That way it is consistent.

**Comment by CarloWood** [comment]
Are you on skype now? I try again

**Comment by davids5** [comment]
Yes

**Comment by CarloWood** [comment]
Doesn't work... "Call failed"

**Pull request merged**
