### PR TITLE
Fix MB85RS256B bug in ramtron

### PR DESCRIPTION
**Pull request by LCaiJie**
MB85RS256B Address Length Error

### CODE REVIEW

**Comment by dagar** [comment]
Is this fixed in upstream NuttX? https://github.com/apache/nuttx

**Comment by LCaiJie** [comment]
> Is this fixed in upstream NuttX? https://github.com/apache/nuttx

image

Not fixed yet, I need to push upstream first?

**Comment by davids5** [comment]
yes @LCaiJie  please do a PR to NuttX. The commit would be `mtd:ramtron MB85RS256B address length is 2`, Once it is merged. Then do a PR here with `[BACKPORT] mtd:ramtron MB85RS256B address length is 2`

**Comment by LCaiJie** [comment]
> yes @LCaiJie please do a PR to NuttX. The commit would be , Once it is merged. Then do a PR here with `mtd:ramtron MB85RS256B address length is 2``[BACKPORT] mtd:ramtron MB85RS256B address length is 2`

https://github.com/apache/nuttx/pull/13380

**Comment by davids5** [comment]
@LCaiJie Please force push with the commit message reading `[BACKPORT] mtd:ramtron MB85RS256B address length is 2`

**Comment by LCaiJie** [comment]
> @LCaiJie Please force push with the commit message reading `[BACKPORT] mtd:ramtron MB85RS256B address length is 2`

OK

**Review by davids5 — APPROVED** [review]

**Comment by davids5** [comment]
@LCaiJie Please do a PR in PX4 that re-points nuttx to px4_firmware_nuttx-10.3.0+ with this change merged.

**Comment by LCaiJie** [comment]
> @LCaiJie Please do a PR in PX4 that re-points nuttx to px4_firmware_nuttx-10.3.0+ with this change merged.

OK

**Comment by LCaiJie** [comment]
@davids5 
https://github.com/PX4/PX4-Autopilot/pull/23694

**Pull request merged**
