### PR TITLE
[BACKPORT] add stm32h755II chip

### PR DESCRIPTION
**Pull request by davids5**
## Testing

@jfbblue0922 - Here is the backport. The PX4 test to bring it in is here https://github.com/PX4/PX4-Autopilot/pull/23265

### CODE REVIEW

**Comment by davids5** [comment]
@julianoes - Would you please test this on the HW you brought https://github.com/PX4/NuttX/pull/214 with?

**Comment by davids5** [comment]
I have verified it on V6X that the value written to STM32_PWR_CR3 is unchanged from before this PR.

**Comment by julianoes** [comment]
@davids5 so this needs testing with CubeOrange+, right? I don't have one with me at the moment.

**Comment by julianoes** [comment]
[cubepilot_cubeorangeplus_default.zip](https://github.com/user-attachments/files/15832893/cubepilot_cubeorangeplus_default.zip)


Here is a .px4 file inside a zip to test this with @bugobliterator.

**Comment by bugobliterator** [comment]
> [cubepilot_cubeorangeplus_default.zip](https://github.com/user-attachments/files/15832893/cubepilot_cubeorangeplus_default.zip)
> 
> Here is a .px4 file inside a zip to test this with @bugobliterator.

Tested working.

**Comment by jfbblue0922** [comment]
@davids5 
Thank you for your response.
I've tested it and found some issues, so I'll create another PR.

**Pull request merged**
