### PR TITLE
Enable 8x oversampling on STM32F40XX UARTs

### PR DESCRIPTION
**Pull request by NaterGator**
We can support baud rates 2x higher by using 8x oversampling. See Table 5 at www.st.com/resource/en/datasheet/stm32f405rg.pdf

### CODE REVIEW

**Comment by davids5** [comment]
@NaterGator 

I think the HW does voting on 3  center samples. 
Did you do the math to determine what % of baud rate error (xtal accuracy of both sides) this change can still faithfully communicate at?

**Comment by NaterGator** [comment]
@davids5 the processor [reference manual](www.st.com/resource/en/reference_manual/DM00031020.pdf) lists these values in tables 144 & 145:
image

The 8x oversampling only kicks in when 16x sampling is no longer possible so this is really up to the user to make sure their equipment is compatible if they want to push the baud rate up.

**Comment by LorenzMeier** [comment]
@davids5 Can you upstream this?

**Comment by davids5** [comment]
@NaterGator, @LorenzMeier 

The spirit of this change is on a PR upstream....

**Comment by NaterGator** [comment]
Thanks @davids5!

**Comment by davids5** [comment]
No - thank you @NaterGator! 

This is now in upstream and will be in nuttx_v3 on my next uptake.

@LorenzMeier - do you want to merge this into master or wait for nuttx_v3 ?

**Comment by LorenzMeier** [comment]
Merge

**Comment by davids5** [comment]
Merged to nuttx_v3

**Pull request merged**
