### PR TITLE
Backport STM32 flash fixes

### PR DESCRIPTION
**Pull request by zehortigoza**

### CODE REVIEW

**Comment by davids5** [comment]
@zehortigoza - 

Nice! 

I will bring these in as a backport patch in the the correct place once https://github.com/PX4/Firmware/pull/6878 come in.

**Comment by davids5** [comment]
@zehortigoza 

For future reference NuttX PR should be on PX4NuttX submodules not in this repo. (This is historical for when NuttX was one repo). But given the series of events and outcome. Full builds need to be done whne contrib to NutttX is going to be done.

There several commits on top of these to get it to build all PX4 and run on non F4 HW.

https://bitbucket.org/nuttx/nuttx/commits/66910577beb4735b0e19ba72dd28be9c5594d91f
https://bitbucket.org/nuttx/nuttx/commits/c2a1b719be908673377454d5634a8d2e19bdbabf

A third commit was also done that does not affect the bin. 

https://bitbucket.org/nuttx/nuttx/commits/fd76a3db05d18989f1c49fb539b62ef3e22d8ae7

I have consolidated all the changes on https://github.com/PX4/Firmware/tree/master_stm32_flash_fixes

in ``` nuttx-patches/00010-BACKPORT-stm32-flash-F4-dcache-corruption-fix-no-HSI-on.patch```

But the upstream change adding the semaphore has broken all the PX4 bootloader build.

I now have to workout a solution for that.

**Comment by davids5** [comment]
Ok that is fixed https://github.com/PX4/Firmware/pull/6885

**Comment by zehortigoza** [comment]
Thanks, nice that you had add a readme here so other people do not get confused like I did.

**Comment by davids5** [comment]
Yes Sorry About that. The week we cut over there was a Serial DMA issue a few days before I took time off for my wedding....I wonder what else I forgot to do :)

**Comment by davids5** [comment]
I was thinking about the the changes you made and what the use case is. I believe I explained the flash params came in from a non threaded very static use. There was an expectation the parm code was locking and serialising access to the flash.  

But since then we had some changes to several parts of the system. I think that there is a potential for some breakage because of the direct use of the up_progmem interface. 

flash param
datman - flash backend

**Comment by davids5** [comment]
@zehortigoza - hit  \<CTRL\> \<CR\> to soon. See edited post above

**Comment by zehortigoza** [comment]
@davids5 sorry I did not fully understand you... are you saying that in theory PX4 would not have a concurrent access to FLASH when using dataman and parameters?

**Comment by davids5** [comment]
I have not diagramed out the code paths but this the concern i have:

I think the api is not transactional:
thread A ------S(L)Flash Unlock S(U)-----------------S(L)Flash Operations - fais flash is lockedS(U)
thread B --...------------------------S(L)Flash LockS(U)----S(w)wwwwwwwwww

If it was transactional:
thread A ------S(L)Flash Unlock ----------------Flash Operations Flash UnlockS(u)
thread B ------------S(w)wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwFlash UnlockS(L).....

**Pull request closed without merging**
