### PR TITLE
Fix cctype (and some ctype.h)

### PR DESCRIPTION
**Pull request by CarloWood**
cctype didn't define anything. This patch puts the
standard functions for unsigned chars and C locale
in namespace std (not wide chars).
Added (std::)isblank and fixed a few minor issues.

As for the coding style, this uses comment blocks like:
//****
//
//****

rather than

/*****
 *
 *****/

because that is what every other file in nuttx/include/cxx
does (and cctype already did).

I copied the exact same comments as ctype.h is using
for the macro's, so surely that should be ok.

Indentation set to 2 spaces (my personal favorite too), even
many files use tabs for indentation, which I had copied
initially.

I opted not to indent the comments and code within the
namespace, since there is no coding style about that,
nor any other example that I could find, and based on
my own (25 years of) experience, that is best. Let me
know if anyone prefers indentation nevertheless.
While the lack of indentation for namespace blocks
is the best approach (I tried with indentation for many
years too), it does lead to confusion where a namespace
begins or ends, or what namespace you are in, unless
you mark the closing brace of the namespace with
'namespace std'. That way you can search for 'namespace'
backwards or forwards and always will find in which
namespace you are in.

Please let me know if anything else needs changing! :)

### CODE REVIEW

**Comment by CarloWood** [comment]
@davids5 To be continued here?

**Comment by nuttx** [comment]
ctype does nothing because of this previous RX4 commit.  According to the author, this change allows use of builtin functions.  According to the author there is no need for #defines or inlines if they are builtin.

Adding logic to replace #defines with inlines would be rejected.

**Comment by nuttx** [comment]
The is the previous PX4 commit that I referred to. This was brought upstream some time ago.

https://github.com/PX4/NuttX/commit/ae4b05e2c51d07369b5d131052099ac346b0841c

**Comment by CarloWood** [comment]
Well that's fine -- but incorrect. What builtin functions? Builtin into what?
When including cctype things simply don't compile.

@LorenzMeier Can you shine a light on this please?

**Comment by davids5** [comment]
@CarloWood 

 FYI: Here is the group discussion when PX4 introduced the changes to PX4 that was take upstream 

https://groups.yahoo.com/neo/groups/nuttx/conversations/messages/7545

We have some sort of disconnect here. 

Would you please render an opinion on, that conversation and where the "built in" may have been coming from and why you are not seeing either duplicate definitions with this change or undefined functions with the existing code base. 

Where all these functions just not used in the whole code base?

**Comment by CarloWood** [comment]
@davids5 Hi, thx for finding that discussion which shows why these #undef's were added in the past.

This is what I understand to be true for,

NUTTX

NuttX is provides full system headers, including standard C++ headers. When completely following the standard, a standard has to be picked (I'd suggest C++11 at this point, not -say- c++14 or c++17). On the other hand, because nuttx aims at embedded systems, it might restrict itself a bit and simply NOT conform to the standard I'd think. One thing it clearly doesn't (want to) support are locale. I'm aware that uClibc++ provides clocale, but I'm talking about NuttX/nuttx/include/cxx.

THE STANDARD (C and C++)

Whether or not compiling C++ (otherwise C), including ctype.h, the standard C header, must be supported and do the same thing in both cases (hence, usage of #ifdef __cplusplus is usually not correct). However, for C it is normal to use macro's when one wants inline functions, certainly for C89. Also the current gcc C99 compiler defines macro's when including ctype.h. These macro's DO however support locale in that they return something that is true for the *current* locale (see  http://pubs.opengroup.org/onlinepubs/009695399/functions/isspace.html ; quote: "The isspace() function shall test whether c is a character of class space in the program's current locale").
And in C++ new functions have been added (to &lt;locale&gt;) with the same name as those defined in ctype.h, but with extra local parameter (overloading). For example, see http://www.cplusplus.com/reference/locale/isspace/
This choice makes it impossible to use macro's for 'isspace' and the other, now overloaded, functions.
Thus, including &lt;ctype.h&gt; from a C++ program defines functions, not macro's.

Including &lt;cctype&gt;, the C++ ISO standard header, defines the same functions but puts them in namespace std.

GCC - or where the #undef's came from.

In the mentioned discussion we see the comment "Remove macros in favor of real functions" literally back as copied from gcc's cctype. And indeed, even now I see this in the cctype file of gcc compilers,
as they contain, for example:

<code><pre>#include &lt;ctype.h&gt;
&nbsp;
#ifndef _GLIBCXX_CCTYPE
#define _GLIBCXX_CCTYPE 1
&nbsp;
// Get rid of those macros defined in <ctype.h> in lieu of real functions.
#undef isalnum
#undef isalpha
#undef iscntrl
#undef isdigit
#undef isgraph
#undef islower
#undef isprint
#undef ispunct
#undef isspace
#undef isupper
#undef isxdigit
#undef tolower
#undef toupper
&nbsp;
namespace std
{
  using ::isalnum;
  using ::isalpha;
  using ::iscntrl;
  using ::isdigit;
  using ::isgraph;
  using ::islower;
  using ::isprint;
  using ::ispunct;
  using ::isspace;
  using ::isupper;
  using ::isxdigit;
  using ::tolower;
  using ::toupper;
} // namespace std
</pre></code>

In that case however, the functions ::isspace et al, in global namespace, exist and have been defined (you see them being dragged into namespace std above) by /usr/include/ctype.h, which is part of the libc6 package; this file contains:

<code><pre>#define __exctype(name) extern int name (int) __THROW
&nbsp;
__BEGIN_NAMESPACE_STD
&nbsp;
/* The following names are all functions:
     int isCHARACTERISTIC(int c);
   which return nonzero iff C has CHARACTERISTIC.
   For the meaning of the characteristic names, see the `enum' above.  */
__exctype (isalnum);
__exctype (isalpha);
__exctype (iscntrl);
__exctype (isdigit);
__exctype (islower);
__exctype (isgraph);
__exctype (isprint);
__exctype (ispunct);
__exctype (isspace);
__exctype (isupper);
__exctype (isxdigit);
</pre></code>
which after preprocessing leads to declarations like:
<code>int isspace(int) throw();</code>
etc.

We do not, and do not want to, include /usr/include/ctype.h when using nuttx though, and since nuttx's ctype.h does NOT define functions in global namespace, but only macro's, undefining those macro's in lieu of real functions is counter productive as we never defined those real functions.

THE SOLUTION

Taking into account that we want <code>#include &lt;cctype&gt;</code> to work, but we do not want to support a full locale system, we DO have the option to simply keep the macro's. But all other files in NuttX/nuttx/include/cxx put declarations in namespace std, so why not keep the #undef's, but add (inline) functions in namespace std, exactly as my patch does ;)

**Comment by davids5** [comment]
Hi @CarloWood, FYI: @Lorenz 

Greg - sent me the link, so I will not take the credit for that. :)

Thank you for the complete picture!

If I follow this, and the time line we have here:

After the upstreaming ```<cctype>``` the the macros were always undefined.

Before the code clean up was done on cpp files that replaced the ```#include <ctype.h>``` with ```#include <cctype>``` - the code built using the macros from ctype.h.

After that "code clean up" the macros were undefined, and new definitions did not exist. Hence the undefined errors. 

So the question I have for @lorenz is, what prompted the submission to upstream of the partial ```<cctype>``` and what was being built with it, that worked?

I think we all agree that:

1) We **do not** want full locale support in NuttX but in fact, we need just enough to keep the compiler happy. Specifically header definitions that are complete enough to compile. - This is from of locale support now in upstream NuttX - as of yesterday and is on nuttx_v3 

2) The inlines make the most sense and are needed when locale is supported. - from purest cpp point of view - they are the correct thing to do.

3) From Greg's perspective inlines replacing macros, do not make sense. 

So here is what I would suggest:

We will merge this in the old Nuttx herein and in nuttx_v3 carry this a patch until a time that it will be considered to be upstreamed.

How does that sound?

**Comment by CarloWood** [comment]
@davids5 Totally correct summary! Also (obviously) I agree with the suggestion at the end. Thanks to Greg for his research in the background what led to the commit in question and finding the commit itself :)

**Comment by LorenzMeier** [comment]
I'm rebasing and applying this and will rely on David to upstream the proper improvements as selected by Greg.

**Pull request merged**
