### PR TITLE
[backport]littlefs and ramtron kconfig updates

### PR DESCRIPTION
**Pull request by Igor-Misic**
## Summary
Backported from upstream needed for PX4 transition to LittleFS. 
upstream RAMTRON PR: https://github.com/apache/nuttx/pull/8496
upstream RAMTRON nsectors size fix: https://github.com/apache/nuttx/pull/8561
upstream LittleFS PR:  https://github.com/apache/nuttx/pull/8453

## Impact
This PR without changing configuration doesn't have any impact on PX4. 

## Testing
Since just those 2 commit doesn't have any impact, this was tested with an additional configuration change at fmu-v5x.
Params were tested with the next config:

```
CONFIG_RAMTRON_EMULATE_SECTOR_SHIFT 0
CONFIG_RAMTRON_EMULATE_PAGE_SHIFT 0
```

1000 cycles were done by setting the random number of params between 1 - 180 with a random value between 0 -  999999 while checking if the BSON file with crash. All cycles were performed without failure. 

An additional test was also performed with LittleFS:
```
CONFIG_FS_LITTLEFS_BLOCK_CYCLE=-1
CONFIG_FS_LITTLEFS_BLOCK_SIZE_FACTOR=128
CONFIG_FS_LITTLEFS_LOOKAHEAD_SIZE=8
CONFIG_FS_LITTLEFS_PROGRAM_SIZE_FACTOR=1
```

I'll test it more intensively but so far no issue.

### CODE REVIEW

**Review by davids5 — COMMENTED** [review]
@Igor-Misic is there a PX4 PR to test this?

**Comment by davids5** [comment]
Please format the commit messages with prefix [BACKPORT] yady

See https://github.com/PX4/NuttX/commits/px4_firmware_nuttx-10.3.0%2B

**Comment by Igor-Misic** [comment]
> @Igor-Misic is there a PX4 PR to test this?

This:
https://github.com/PX4/PX4-Autopilot/pull/21134

But now I am thinking to split LittleFS PR from RAMTRON to 1-byte granularity to reduce the chance of error.

**Comment by davids5** [comment]
@Igor-Misic do you need to set these PRs to Draft until you are done? 

This one: https://github.com/PX4/PX4-Autopilot/pull/21134 too?

**Comment by Igor-Misic** [comment]
@davids5 here is the PR to test it: https://github.com/PX4/PX4-Autopilot/pull/21204

**Review by davids5 — APPROVED** [review]
LGTM

**Pull request merged**
