### PR TITLE
Add stm32h755II chip

### PR DESCRIPTION
**Pull request by jfbblue0922**
## Summary

Our flight controller uses stm32h7x5.
We are issuing this PR to make it compatible with PX4.

## Impact

Add CONFIG_STM32H7_STM32H7X5XX into the program.

## Testing

We have confirmed that the firmware works correctly on PX4.

### CODE REVIEW

**Comment by davids5** [comment]
@jfbblue0922 The should go upstream to Nuttx and com back to PX4 as a backport. 

Please have a look at the way the the part number [chooses the Pinning](https://github.com/PX4/NuttX/pull/304/files#diff-7b589cd0d04d9d7c39e76668e6cca5841ccae1854e6c4d304effdbbe040de283R111-R118) and see if you can support more versions of the stm32h7x5. Once it is upstream ping me in that PR and we will review it there.

**Comment by jfbblue0922** [comment]
@davids5 

Thank you for your advice.

I added 'peripherals' to all stm32h7x5xx chips.

What is upstream?
We cannot understand because we lack knowledge.
Please tell me what we should do next.

**Comment by davids5** [comment]
> @davids5
> 
> Thank you for your advice.
> 
> I added 'peripherals' to all stm32h7x5xx chips.
> 
> What is upstream? We cannot understand because we lack knowledge. Please tell me what we should do next.

Do your pull request against. https://github.com/apache/nuttx

I and others will review it upstream.

We will then [Backport](https://www.crowdstrike.com/cybersecurity-101/backporting/) it to this repo once it is accepted upstream.

**Comment by jfbblue0922** [comment]
@davids5

we have made PR. https://github.com/apache/nuttx

thank you.

**Comment by jfbblue0922** [comment]
@davids5 

apache nuttx master has been merged, so I pushed PX4 nuttx to this PR.

Thank you.

**Comment by davids5** [comment]
@jfbblue0922 I did the backport from upstream here https://github.com/PX4/NuttX/pull/311

Please see https://github.com/PX4/PX4-Autopilot/pull/23265. Please test it and ensure it works for you. Then close this PR

**Comment by davids5** [comment]
Replaced by https://github.com/PX4/NuttX/pull/311 & https://github.com/PX4/NuttX/pull/313

**Pull request closed without merging**
