### PR TITLE
[Backport] SocketCAN support

### PR DESCRIPTION
**Pull request by PetervdPerk-NXP**
Based on the SocketCAN branch from https://github.com/PetervdPerk-NXP/incubator-nuttx/tree/SocketCAN.

This PR adds SocketCAN support including the FlexCAN driver used in the S32K1XX.

Unfortunately due to the NuttX code style changes cherry picking was hard and some lines are backports of the NXstyle compliance as well. If someone has tips to avoid this please contact me.

### CODE REVIEW

**Comment by dagar** [comment]
This is a bit hard to actually review. I'll put this together with a PX4/Firmware branch so we can check for any regressions and test the new support.

**Review by LorenzMeier — DISMISSED** [review]

**Comment by PetervdPerk-NXP** [comment]
@dagar indeed that would be the best idea

**Comment by PetervdPerk-NXP** [comment]
So due to NXStyle more files to changed then supposed too. @dagar could you rerun the CI again?

**Comment by dagar** [comment]
> So due to NXStyle more files to changed then supposed too. @dagar could you rerun the CI again?

I've updated the PX4/NuttX branch and PX4/Firmware PR https://github.com/PX4/Firmware/pull/14518.

**Comment by davids5** [comment]
@dagar - Since this touches the net interfaces we should test this on V5x for regressions.

**Comment by dagar** [comment]
I did a very quick networking sanity test on the av_x-v1 board and it seems fine.

**Review by dagar — APPROVED** [review]

**Pull request merged**
