### PR TITLE
[BACKPORT] master_k66_ethernet (pull request #1064)

### PR DESCRIPTION
**Pull request by davids5**
NXP k66 Ethernet

* Kinetis:Add TJA1100 Phy 
Submitted by Peter.vanderperk@nxp.com 
 
* Kinetis:enet.c formated with nxstyle

* net:mii Cleanup TJA1100 Support

 Formating and adding mask and shifts

* net:Kconfig Cleanup formatting

Approved-by: Gregory Nutt <gnutt@nuttx.org>

### CODE REVIEW

**Comment by davids5** [comment]
@julianoes , @dagar as discussed on the dev call this can com in after the release.

**Comment by julianoes** [comment]
@dinomani please review

**Review by dagar — APPROVED** [review]

**Comment by dk7xe** [comment]
Gentlemen, when will this be merged?

**Comment by davids5** [comment]
Superseded by The Nuttx upgrade to 8.2 and @igalloway confirming backport to 1.10 was not needed.

**Pull request closed without merging**
