### PR TITLE
drivers/mtd: add support to Macronix MX25LF25635F serial NOR flash

### PR DESCRIPTION
**Pull request by Lampoo**
Add support to Macronix MX25LF25635F SPI NOR flash

### CODE REVIEW

**Comment by dagar** [comment]
Is this a backport from upstream NuttX or new work?

**Comment by Lampoo** [comment]
@dagar No, it is not a back port, the upstream doesn't include support to MX25LF25635F. However the SPI driver can be shared for series of MX25L NOR flash. The patch itself only adds necessary IDs and geometry information to the driver to recognize it.

**Comment by davids5** [comment]
@Lampoo would you please submit this upstream to NuttX and then do a back port PR here in.

**Comment by davids5** [comment]
Upstreamed and back ported here https://github.com/PX4/NuttX/pull/39

**Review by davids5 — COMMENTED** [review]
@Lampoo - thank you this has been upstreamed and back ported here https://github.com/PX4/NuttX/pull/39

**Comment by Lampoo** [comment]
@davids5 oh, what a surprise, Thanks for the helping ;)

**Pull request closed without merging**
