### PR TITLE
Missing files - DNM

### PR DESCRIPTION
**Pull request by jfbblue0922**
## Summary
After testing #311 , I found some things that we would like you to fix.
I added the definition of stm32h755II because it was missing.

### CODE REVIEW

**Comment by davids5** [comment]
@jfbblue0922 Does this need to Go Upstream?

**Comment by jfbblue0922** [comment]
@davids5 
It's already been merged upstream, so there's no need to go it.
Thank you.

**Comment by davids5** [comment]
> @davids5 It's already been merged upstream, so there's no need to go it. Thank you.

To be clear: These changes in this PR are already in upstream? If that is the case Please find the commits in upstream so we can backport that set of commits here. We do not want to diverge

**Comment by jfbblue0922** [comment]
@davids5 
In adding the stm32h755II,
I made two PRs in apache/nuttx.git and they were merged.

#12350 add stm32h755II chip
#12394 Re-PR add stm32h755II chip

But, I noticed that #12350 was missing.
Therefore, I made this PR again.

**Comment by davids5** [comment]
Replace by https://github.com/PX4/NuttX/pull/313

**Pull request closed without merging**
